#!/usr/bin/env node
/**
 * mock-copilot — Mock AI Agent for Code Explorer Testing
 *
 * A mock executable that behaves like an LLM CLI agent. Given a prompt
 * (via stdin), it returns a structured document echoing back the input
 * prompt, the date of the call, and any CLI arguments provided.
 *
 * The response is delayed by a configurable number of milliseconds
 * (default: 3000ms) to simulate real LLM latency.
 *
 * Usage:
 *   echo "Analyze this function" | node tools/mock-copilot.js [--delay <ms>] [--output-format text] [...]
 *
 * Environment:
 *   MOCK_COPILOT_DELAY_MS — Override the default delay (3000ms).
 *
 * The output format mirrors what the ResponseParser expects:
 *   - A ### Overview section
 *   - A json:symbol_identity block (if the prompt contains cursor context)
 *   - Echo of the input prompt and arguments for test verification
 */

const args = process.argv.slice(2);

// Parse --delay flag from CLI args, or fall back to env, or default 3000ms
let delayMs = 3000;
const delayArgIdx = args.indexOf('--delay');
if (delayArgIdx !== -1 && args[delayArgIdx + 1]) {
  delayMs = parseInt(args[delayArgIdx + 1], 10);
  if (isNaN(delayMs) || delayMs < 0) {
    delayMs = 3000;
  }
} else if (process.env.MOCK_COPILOT_DELAY_MS) {
  const envDelay = parseInt(process.env.MOCK_COPILOT_DELAY_MS, 10);
  if (!isNaN(envDelay) && envDelay >= 0) {
    delayMs = envDelay;
  }
}

// Collect stdin
let stdinData = '';
process.stdin.setEncoding('utf8');
process.stdin.on('data', (chunk) => {
  stdinData += chunk;
});

process.stdin.on('end', () => {
  const now = new Date().toISOString();
  const promptLength = stdinData.length;
  const promptPreview = stdinData.substring(0, 500).replace(/\n/g, '\\n');

  // Build the mock response document
  const response = buildResponse(now, promptLength, promptPreview, args, stdinData);

  // Delay then output
  setTimeout(() => {
    process.stdout.write(response);
    process.exit(0);
  }, delayMs);
});

// Handle stdin being closed immediately (no data)
process.stdin.on('error', () => {
  process.stderr.write('mock-copilot: error reading stdin\n');
  process.exit(1);
});

/**
 * Build a mock analysis response that resembles real LLM output.
 * Includes structured JSON blocks that ResponseParser can extract.
 */
function buildResponse(timestamp, promptLength, promptPreview, cliArgs, fullPrompt) {
  // Try to detect the symbol name from the prompt
  let symbolName = 'mockSymbol';
  let symbolKind = 'function';
  const wordMatch = fullPrompt.match(/word["":\s]+["']?(\w+)["']?/i);
  if (wordMatch) {
    symbolName = wordMatch[1];
  }
  const kindMatch = fullPrompt.match(/kind["":\s]+["']?(\w+)["']?/i);
  if (kindMatch) {
    symbolKind = kindMatch[1];
  }

  const filteredArgs = cliArgs.filter((a, i) => {
    // Remove --delay and its value from the echoed args
    if (a === '--delay') return false;
    if (i > 0 && cliArgs[i - 1] === '--delay') return false;
    return true;
  });

  return `### Overview

This is a mock analysis generated by **mock-copilot** for testing purposes.

**Symbol**: \`${symbolName}\` (${symbolKind})
**Generated at**: ${timestamp}
**Prompt length**: ${promptLength} characters
**CLI arguments**: ${filteredArgs.length > 0 ? filteredArgs.join(' ') : '(none)'}

The mock-copilot agent received the prompt and is echoing it back as a structured analysis document. This response is intentionally deterministic to enable reliable testing of the Code Explorer analysis pipeline.

### Key Points

- Mock analysis provider for testing — no real AI processing
- Prompt was ${promptLength} characters long
- Response generated at ${timestamp}
- CLI args: [${filteredArgs.map(a => '"' + a + '"').join(', ')}]

### Potential Issues

- This is a mock response and does not contain real code analysis
- Use a real LLM provider (copilot-cli, mai-claude) for actual analysis

\`\`\`json:symbol_identity
{
  "name": "${symbolName}",
  "kind": "${symbolKind}",
  "container": null,
  "scopeChain": []
}
\`\`\`

\`\`\`json:callers
[]
\`\`\`

\`\`\`json:steps
[
  { "step": 1, "description": "Mock step: received prompt (${promptLength} chars)" },
  { "step": 2, "description": "Mock step: generated response at ${timestamp}" }
]
\`\`\`

\`\`\`json:subfunctions
[]
\`\`\`

\`\`\`json:diagrams
[
  {
    "title": "Mock Flow",
    "type": "flowchart",
    "mermaidSource": "flowchart LR\\n  A[Input Prompt] --> B[mock-copilot]\\n  B --> C[Mock Response]"
  }
]
\`\`\`

### Mock Metadata

| Field | Value |
|-------|-------|
| Provider | mock-copilot |
| Timestamp | ${timestamp} |
| Delay | ${delayMs}ms |
| Prompt Length | ${promptLength} chars |
| Args Count | ${filteredArgs.length} |

### Input Prompt Preview

\`\`\`
${promptPreview}
\`\`\`
`;
}
